### ISSUE TITLE
creative.min.css not updating on changes to creative.css?

### ISSUE THREAD

**Issue by itsanolive** [vvalchev/creative-theme-jekyll-new#6]
I'm not understanding when/how the minification is happening on the creative.css file - if i change .css, min.css is not updated. What am I missing?

**Comment by vvalchev** [comment]
It wasn't supposed to modify creative.css or creative.min css. It comes from the theme - https://startbootstrap.com/template-overviews/creative.

If you want to add extra css, you should put it into `_sass` folder and reference it it `_layouts/base.html`

**Comment by vvalchev** [comment]
I just did a tiny change, that will automatically compress the css. (see https://github.com/vvalchev/creative-theme-jekyll-new/commit/879769e6202d967b8ede22ad7341c3b0c33ef2a9)

Anyway, I think if you want to change something in the theme you should build it from it's original source.
