### ISSUE TITLE
Animations missing

### ISSUE THREAD

**Issue by level3guillermo** [vvalchev/creative-theme-jekyll-new#8]
Looks like the animations are all stripped on this version when compared to the original.
Just wondering if this was on purpose. I've been trying to apply them to this theme but anything I do does not seem to work.

Apologies if this is not the correct avenue for this topic!

**Comment by vvalchev** [comment]
Hello @level3guillermo ,
Did you opened https://vvalchev.github.io/creative-theme-jekyll-new/ ? All the animation there seems to be working correctly. But I also noticed, that the animation works only when you have a relative (within the page) links, with anchors.
E.g the one below will show the animation

```
<a href="#services">Services</a>
```

But no animation will be shown on:
```
<a href="/#services">Services</a>
<a href="links">Links</a>
<a href="/contact#map">Contacts</a>
```

**Comment by level3guillermo** [comment]
> Hello @level3guillermo ,
> Did you opened https://vvalchev.github.io/creative-theme-jekyll-new/ ? All the animation there seems to be working correctly. But I also noticed, that the animation works only when you have a relative (within the page) links, with anchors.
> E.g the one below will show the animation
> 
> ```
> <a href="#services">Services</a>
> ```
> 
> But no animation will be shown on:
> 
> ```
> <a href="/#services">Services</a>
> <a href="links">Links</a>
> <a href="/contact#map">Contacts</a>
> ```

Thanks for the response!
I'm specifically referring to the "visibility: visible; animation-name: bounceIn;" and "style="visibility: visible; animation-name: tada;"" (these are used in the "at your service", "download now" button, and the lets get in touch icons)
that are in use in the original template by volny (https://volny.github.io/creative-theme-jekyll/)

The animation for navigating to different anchors seems to work perfect on your version.

**Comment by vvalchev** [comment]
You are right. Those animations are not there. Probably due to the reason, that I started from the original theme https://startbootstrap.com/themes/creative/, not by forking volny theme. Maybe he added some fancy stuff.

**Comment by level3guillermo** [comment]
> You are right. Those animations are not there. Probably due to the reason, that I started from the original theme https://startbootstrap.com/themes/creative/, not by forking volny theme. Maybe he added some fancy stuff.

Well that's embarrassing! Sorry for the bother and thank you for taking the time to reply!
