### ISSUE TITLE
Upgrade Jekyll

### ISSUE THREAD

**Issue by antgel** [vvalchev/creative-theme-jekyll-new#9]
Hi, thanks for this great theme!

It would be great to see an upgrade to the latest Jekyll (4.1.1 at the time of writing).

**Comment by vvalchev** [comment]
Hello Antony,
It is now using `jekyll = 3.9.0`. It is not 4.1.1 but I want to keep it compatible with github-pages.

**Comment by antgel** [comment]
Ah, fair enough. I'm not using GitHub Pages. I'll close this in the hope that we can upgrade when they do. :)
